# Matt DeMichele Resume (Based on Jekyll Resume Theme)

# Site settings
title: Matt DeMichele Resume
email: m.d.demichele@domain.com
description: Software Engineer and Computer Science Student
baseurl: ""
url: ""
name: Matt DeMichele
job: Software Engineer
location: Phoenix, AZ
languages: C, JavaScript, Python, HTML, and CSS
github_username:  mdemichele
linkedin_username:  matthew-demichele-3a51a9139
email_address: m.d.demichele@gmail.com
medium: mattdemichele
# Build settings
markdown: kramdown
plugins: 
  - rcsv